# Generated by Django 6.0.5 on 2026-05-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la technologie')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Architecture et défis')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image (Ex: Cloudinary)")),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('link_demo', models.URLField(blank=True, null=True, verbose_name='Lien de la Démo')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-Stack', 'Full-Stack'), ('Cybersécurité', 'Cybersécurité'), ('Mobile', 'Mobile')], default='Full-Stack', max_length=50, verbose_name='Catégorie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technologies', models.ManyToManyField(related_name='projects', to='projects.technology', verbose_name='Technologies utilisées')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
