# Generated by Django 6.0.5 on 2026-05-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre (Rôle ou Diplôme)')),
                ('institution', models.CharField(max_length=200, verbose_name='Établissement / Entreprise')),
                ('start_year', models.CharField(max_length=4, verbose_name='Année de début')),
                ('end_year', models.CharField(blank=True, max_length=10, verbose_name="Année de fin (ou 'Présent')")),
                ('description', models.TextField(blank=True, verbose_name='Description des tâches/apprentissages')),
                ('entry_type', models.CharField(choices=[('Education', 'Diplôme / École'), ('Experience', 'Expérience Pro')], default='Education', max_length=20, verbose_name='Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage (0 = plus haut)")),
            ],
            options={
                'verbose_name': 'Étape de parcours',
                'verbose_name_plural': 'Parcours (CV)',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Votre Nom', max_length=100, verbose_name='Nom complet')),
                ('hero_title', models.CharField(max_length=200, verbose_name="Titre d'accroche (Hero)")),
                ('hero_subtitle', models.TextField(blank=True, verbose_name="Sous-titre d'accroche")),
                ('about_text', models.TextField(verbose_name="Texte de section 'À propos'")),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='Fichier CV')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('available_for_hire', models.BooleanField(default=True, verbose_name='Disponible pour des projets ?')),
            ],
            options={
                'verbose_name': 'Profil Global',
                'verbose_name_plural': 'Profil Global',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom (ex: React)')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('DevOps', 'DevOps'), ('Soft', 'Soft Skill'), ('Other', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('mastery_percentage', models.PositiveIntegerField(default=80, verbose_name='Maîtrise (%)')),
                ('icon_name', models.CharField(blank=True, help_text="Nom d'icône pour le frontend (ex: 'react')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'name'],
            },
        ),
    ]
