# Generated by Django 6.0.5 on 2026-05-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='URL de la photo de profil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.PositiveIntegerField(default=3, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_count',
            field=models.PositiveIntegerField(default=12, verbose_name='Projets livrés'),
        ),
        migrations.AddField(
            model_name='profile',
            name='technologies_count',
            field=models.PositiveIntegerField(default=20, verbose_name='Technologies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='Lien WhatsApp'),
        ),
    ]
