# Generated by Django 6.0.5 on 2026-05-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_avatar_url_profile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse email de contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localisation'),
        ),
    ]
