# Generated by Django 6.0.5 on 2026-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_contact_email_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_page_description',
            field=models.TextField(default="Architecture d'entreprise, audit de sécurité ou produit web innovant — n'hésitez pas à me contacter. Je réponds dans les 24h.", verbose_name='Description page Contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_page_title',
            field=models.CharField(default='Parlons de votre projet', max_length=200, verbose_name='Titre page Contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cta_description_active',
            field=models.TextField(default="Basé sur les standards de l'industrie, je transforme vos idées en produits robustes.", verbose_name='Description CTA (disponible)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cta_description_inactive',
            field=models.TextField(default='Le portfolio reste consultable en continu, avec des contenus éditables depuis le dashboard.', verbose_name='Description CTA (indisponible)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cta_headline_active',
            field=models.CharField(default='Prêt à sécuriser & scaler vos applications ?', max_length=200, verbose_name='Titre CTA (disponible)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cta_headline_inactive',
            field=models.CharField(default='Découvrez mon portfolio', max_length=200, verbose_name='Titre CTA (indisponible)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='footer_copyright',
            field=models.TextField(default='© {year} — Tous droits réservés.', verbose_name='Texte copyright footer'),
        ),
    ]
