# Generated by Django 6.0.5 on 2026-05-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile_contact_page_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='technologies_count',
        ),
    ]
