# Generated by Django 6.0.5 on 2026-05-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience (Overide)"),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de projets (Overide)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='technologies_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de technos (Overide)'),
        ),
    ]
