# Generated by Django 6.0.5 on 2026-05-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profile_experience_years_profile_projects_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name="Texte de section 'À propos'"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='', verbose_name="Sous-titre d'accroche"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Titre d'accroche (Hero)"),
        ),
    ]
