# Generated by Django 6.0.5 on 2026-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_profile_about_text_alter_profile_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL de la photo de profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lien Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lien GitHub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lien LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lien WhatsApp'),
        ),
    ]
