# Generated by Django 6.0.5 on 2026-05-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_profile_avatar_url_alter_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL image externe (fallback)'),
        ),
    ]
