# Generated by Django 6.0.5 on 2026-05-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_image_alter_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Photo de profil (Upload)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL de la photo de profil (Fallback)'),
        ),
    ]
