# Generated by Django 6.0.5 on 2026-05-31 16:32

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_avatar_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=portfolio.models.get_cv_storage, upload_to='cv/', verbose_name='Fichier CV (PDF)'),
        ),
    ]
